baseURL: https://viz.cernu.us
languageCode: en-us
title: Tricia's Advent of Code
theme: PaperMod
copyright: "Copyright © 2024 Tricia Bogen"

enableEmoji: true
enableRobotsTXT: true
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: Tricia Bogen
  defaultTheme: dark
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  UseHugoToc: true

  description: |
    A chronicle of one girl's experience making pretty animations from Advent of
    Code puzzles.

  images: [ "images/font-demo.gif" ]

  homeInfoParams:
    title: Tricia × Advent of Code
    Content: |
      Hi! It's me! Your friendly neighborhood Tricia! Welcome to `viz`, a
      little site mostly focused on my visualization work for Advent of Code.
      Hope you enjoy reading!

      ## About Me

      I'm a security & infrastructure engineer. I mostly work on very large
      Internet systems, usually dealing with things like Go, Terraform, and
      AWS. In my spare time I enjoy baking, woodworking, sailing, circus
      aerials, rock climbing, bicycling, and video games. I live with my wife
      in San Francisco, where we raise our darling cat Chell.

  mainSections:
    - 2024
    - 2022
    - 2021

  social: true
  socialIcons:
    - name: mastodon
      url: https://tech.lgbt/@tricia
    - name: github
      url: https://github.com/asymmetricia
    - name: rss
      url: index.xml

sectionPagesMenu: main

menu:
  main:
    - identifier: 2024
      name: 2024
      url: /2024/
    - identifier: 2022
      name: 2022
      url: /2022/
    - identifier: 2021
      name: 2021
      url: /2021/

deployment:
  targets:
    - name: "viz.cernu.us"
      URL: "s3://viz-cernu-us?region=us-west-1"
      cloudFrontDistributionID: E159E0YQ6AVWL5
